export const api_path = {
    login: "api/users/login/",
    alarm: "alarm/",
    sensor: "sensor/",
    brixline: "brixline/",
    brixlinemin: "brixlinemin/",
    brixlinemax: "brixlinemax/",
    brixlinetarget: "brixlinetarget/",
    brix: "brix/",
    brixmin: "brixmin/",
    brixmax: "brixmax/",
    brixavg: "brixavg/",
    templine: "templine/",
    templinemin: "templinemin/",
    templinemax: "templinemax/",
    templinetarget: "templinetarget/",
    temp: "temp/",
    tempmin: "tempmin/",
    tempmax: "tempmax/",
    tempavg: "tempavg/",
  };